### ISSUE TITLE
Замечания и пожелания

### ISSUE THREAD

**Issue by vlmaksime** [quarckster/vsetv.com-grabber#4]
Спасибо за скрипт. Прикрутил его к tvheadend, теперь у меня есть телепрограмма на все каналы, транслируемые по iptv.

Теперь о печальном. Замечания:
1. Можно в качестве id канала использовать его наименование на транслите?
Использование числового идентификатора не удобно, т.к. нумерация сбивается каждый раз, после добавления/удаления каналов в списке избранных. Т.к. в tvheadend'e привязка каналов происходит по идентификатору, порядок сбивается и приходится все каналы подвязывать по новой.
2. Не учитывается часовой пояс.
Сейчас во времени передач не учитывается часовой пояс. Из-за этого произошел сдвиг на 3 часа.

Пожелание.
Можно добавить описание передачи?

**Comment by quarckster** [comment]
1. Id канала это теперь его имя на транслите.
2. Часовой пояс следует выставить в настройках сайта.
3. vsetv.com предоставляет описание только к фильмам и сериалам. Причём у каждой серии сериала будет одно и то же описание. Не думаю, что такая информация будет полезной.
